
//PRODUCTS TYPES

export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_ID = "GET_PRODUCT_ID";
export const ORDER_BY_PRICE_ASC = "ORDER_BY_PRICE_ASC";
export const ORDER_BY_PRICE_DESC = "ORDER_BY_PRICE_DESC";
export const FILTER_BY_SEASON = "FILTER_BY_SEASON";
export const FILTER_BY_GENRE = "FILTER_BY_GENRE";
export const REMOVE_FILTER_GENRE = "REMOVE_FILTER_GENRE";
export const FILTER_BY_TYPE = "FILTER_BY_TYPE";
export const REMOVE_FILTER_TYPE = "REMOVE_FILTER_TYPE";

//CART TYPES